version: '3.8'

services:
  api-server:
    build: ./api-server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - SESSION_SECRET=dev-session-secret-key
      - DATABASE_URL=file:./dev.db
      - REDIS_URL=redis://redis:6379
      - DEV_ALLOW_REGISTER=true
    volumes:
      - ./api-server:/app
      - /app/node_modules
    depends_on:
      - redis
    restart: unless-stopped
    command: npm run dev

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis_data:
