name: SSH Connectivity Check (Debug v2)

on:
  workflow_dispatch:

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      # Load your private key only (keep as a secret)
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Hardcode the values to avoid any secrets/formatting issues
      - name: Define connection vars (hardcoded for debug)
        shell: bash
        run: |
          echo "HOST=192.168.86.30" >> "$GITHUB_ENV"
          echo "PORT=2222" >> "$GITHUB_ENV"
          echo "USER=evantrafton" >> "$GITHUB_ENV"
          echo "APP_DIR=/opt/apps/dashboard" >> "$GITHUB_ENV"

      - name: Show debug values
        shell: bash
        run: |
          echo "HOST=$HOST"
          echo "PORT=$PORT"
          echo "USER=$USER"
          echo "APP_DIR=$APP_DIR"

      - name: Add server to known_hosts (non-fatal)
        shell: bash
        run: |
          mkdir -p ~/.ssh
          # Try to fetch host key; don't fail the job if ssh-keyscan can't reach
          ssh-keyscan -T 10 -p "$PORT" "$HOST" >> ~/.ssh/known_hosts 2>/dev/null || true
          test -s ~/.ssh/known_hosts && echo "known_hosts populated" || echo "known_hosts empty (will rely on StrictHostKeyChecking=no)"

      - name: SSH test (whoami/hostname + writability)
        shell: bash
        run: |
          # First try with host key checking; if that fails, try once with it disabled
          if ssh -o StrictHostKeyChecking=yes -p "$PORT" "$USER@$HOST" "whoami && hostname && test -w '$APP_DIR' && echo 'APP_DIR is writable ✅'"; then
            exit 0
          else
            echo "Retrying with StrictHostKeyChecking=no..."
            ssh -o StrictHostKeyChecking=no -p "$PORT" "$USER@$HOST" "whoami && hostname && test -w '$APP_DIR' && echo 'APP_DIR is writable ✅'" || exit 1
          fi
