name: SSH Connectivity Check (Debug)

on:
  workflow_dispatch:

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # keep the key as a secret

      - name: Define connection vars (hardcoded for debug)
        shell: bash
        run: |
          echo "HOST=192.168.86.30" >> $GITHUB_ENV
          echo "PORT=2222" >> $GITHUB_ENV
          echo "USER=evantrafton" >> $GITHUB_ENV
          echo "APP_DIR=/opt/apps/dashboard" >> $GITHUB_ENV

      - name: Add server to known_hosts
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          ssh-keyscan -p "$PORT" "$HOST" >> ~/.ssh/known_hosts

      - name: Test writability and whoami
        shell: bash
        run: |
          set -euo pipefail
          ssh -o StrictHostKeyChecking=yes -p "$PORT" "$USER@$HOST" "\
            whoami && hostname && \
            test -w '$APP_DIR' && echo 'APP_DIR is writable ✅' || (echo 'APP_DIR not writable ❌' && exit 1)"
